CREATE TABLE "bookings" (
	"id" serial PRIMARY KEY NOT NULL,
	"hotel_id" varchar(255) NOT NULL,
	"hotel_name" varchar(255) NOT NULL,
	"room_id" integer NOT NULL,
	"room_name" varchar(255) NOT NULL,
	"guest_name" varchar(255) NOT NULL,
	"guest_email" varchar(255) NOT NULL,
	"guest_phone" varchar(50),
	"checkin_date" date NOT NULL,
	"checkout_date" date NOT NULL,
	"adults" integer NOT NULL,
	"children" integer DEFAULT 0,
	"total_price" numeric(10, 2) NOT NULL,
	"currency" varchar(10) NOT NULL,
	"booking_status" varchar(50) DEFAULT 'confirmed' NOT NULL,
	"special_requests" varchar(1000),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
